### ISSUE TITLE
apache class overwrite not working

### ISSUE THREAD

**Issue by rspiak** [sgnl05/sgnl05-racktables#10]
Hi,

could you please initialize the apache class only if it has not yet already been initialized ?
I'd suggest to wrap lines 14 to 20 of  sgnl05-racktables/manifests/apache.pp within an if statement.

Reason I'd like that is that I need to harden apache security with 

```
    trace_enable     => 'Off',
    server_signature => 'Off',
    server_tokens    => 'Prod',
```

and I'm unable to call the apache class "again" :)

Thank you and also thanks for the hard work put into the racktables puppet module.

**Comment by raoulbhatia** [comment]
Hi - I would also be looking for this functionality - is this project still alive?
